export const fakeData=[
    {
        id:1,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:2,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:3,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:4,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:5,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:6,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:7,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:8,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:9,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:10,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:11,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:12,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:13,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:14,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:15,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:16,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:17,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:18,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:19,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },
    {
        id:20,
        logo:"https://i.pinimg.com/736x/3c/ff/4a/3cff4a0b2b76cdb2fddef84b35056c74.jpg",
        postName:"Junior Front End Developer",
        companyName:"LionIT LTD",
        postedBy:"Abdullah Al Rafee",
        location:"Dhaka",
        jobType:"Full-Time",
    },

]